# Generated by Django 5.0.2 on 2024-03-15 11:28

from django.db import migrations
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_recipeingredient_recipe'),
    ]

    operations = [
            migrations.AddField(
        model_name='recipe',
        name='created_on',
        field=models.DateTimeField(auto_now_add=True, default=timezone.now),  # Adjust default as needed
    ),
        
]
